#!/bin/sh

set -e
#set -x

trap 'rm "$config"; rm "$known_hosts";' EXIT

config=$(mktemp)
known_hosts=$(mktemp)

fnmatch () { case "$2" in $1) return 0 ;; *) return 1 ;; esac ; }

[ -f ~/.ssh/config.head ] && cat ~/.ssh/config.head > $config || true

for dir in ~/.ssh/hosts.d/*;
do
	host=$(basename "$dir")

	if [ -d "$dir" ];
	then
		if [ -f "$dir/known_hosts" ];
		then
			cat "$dir/known_hosts" >> $known_hosts
		fi

		if [ -f "$dir/config" ];
		then
			echo "" >> $config
			echo "# >> BEGIN $host" >> $config

			if [ -x "$dir/config" ];
			then
				# STDOUT goes to config file
				# fd/3 goes to STDOUT
				# fd/4 goes to known_hosts
				. "$dir/config" 3>&1 >> $config 4>> $known_hosts
			else
				echo "Host $host" >> $config
				cat "$dir/config" >> $config 
			fi

			echo "# >> END $host" >> $config
			echo "" >> $config
		fi
	fi
done

[ -f ~/.ssh/config.tail ] && cat ~/.ssh/config.tail >> $config || true

cat $config > ~/.ssh/config
cat $known_hosts > ~/.ssh/known_hosts
