#!/bin/sh

user=chris.smith

git_cat_file()
{
	repo="$1"
	file="$2"

	if [ -n "$3" ];
	then
		branch="-b '$3'"
	else
		branch=
	fi

	dir=$(mktemp -d)

	git clone --depth 1 $branch -q --bare "$repo" "$dir" >/dev/null
	git --no-pager --git-dir="$dir" show "HEAD:$file"

	rm -rf "$dir"
}

if ! network-location work;
then
	# Inside work network known hosts are deployed via Puppet.
	# So outside the network we attempt to pull these hosts out of git.
	git_cat_file wp:puppet modules/ssh/files/known_hosts >&4 || true
fi

echo "Host $host"
echo "User $user"
echo "IdentityFile ~/.ssh/chris.smith@widerplan.com"
echo "ForwardAgent yes"
echo "ForwardX11 yes"

if network-location work;
then
	# Allow Likewise to authenticate requests when on the work network.
	[ -f /etc/likewise-open ] && echo "GSSAPIAuthentication yes" || true
else
	echo "GSSAPIAuthentication no"
fi
